openapi: 3.0.0
info:
  version: 1.0.0
  title: Fashion Project Orders API
  description: API to manage orders. This API communicates with the Fashion Project API; by Juanny MIENAHATA & Lina BELAKHDAR
servers:
  - url: http://localhost:3000
    description: Local Server
tags:
  - name: orders
    description: Operations about orders
paths:
  /api/order:
    get:
      tags:
        - orders
      description: Get all orders
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '500':
          description: Internal Server Error
    post:
      tags:
        - orders
      description: Create one or more orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                articles:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 20a22d42-a984-4fcf-bc6d-fc5e8148665e
                      size:
                        type: string
                        enum:
                          - S
                          - M
                          - L
                          - XL
                status:
                  type: string
                  enum:
                    - IN PROGRESS
                    - CANCELED
                    - COMPLETED
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    delete:
      tags:
        - orders
      description: Delete all orders
      responses:
        '200':
          description: Success
        '500':
          description: Internal Server Error
  /api/order/{id}:
    get:
      tags:
        - orders
      description: Get an order by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - orders
      description: Delete an order by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '404':
          description: 'Error : Order not found'
    put:
      tags:
        - orders
      description: Modify an order by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                articles:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      size:
                        type: string
                status:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: 'Error : You can''t modify this order. The order is completed or canceled.'
        '500':
          description: Internal Server Error
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          example: 565ba177-a726-4d6e-9e85-f559b9a1efe9
        articles:
          type: string
          example: '[{"id":"af68e4fc-4f58-4403-80f8-6bbd1980443c","size":"M"},{"id":"af68e4fc-4f58-4403-80f8-6bbd1980443c","size":"S"}]'
        totalprice:
          type: number
          example: 40
        status:
          type: string
          enum:
            - IN PROGRESS
            - COMPLETED
            - CANCELED
        createdAt:
          type: string
          example: '2024-04-23T11:58:08.696Z'
      required:
        - id
        - articles
        - totalprice
        - status
        - createdAt
